### ISSUE TITLE
Crash of click by Trade in the new Menü

### ISSUE THREAD

**Issue by Titoo8899** [AustereTony-MCMods/Oxygen-Trade#1]
Hi,
the Trade crash the game. I have open the new Menü and have the Trade click. The Game have in 2 seconds crash. I have a crash report and hope you can fix it.

Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Currency Provider Core Plugin (oxygen-cp-grand-economy-1.12.2-0.9.0.jar)
  Oxygen Core Plugin (oxygen-core-1.12.2-0.9.0.jar)
  FMLModule (mdxlib-3.0.0.20.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  FirstAid CoreMod (firstaid-core-1.6.3.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
  Players List Core Plugin (oxygen-players-list-1.12.2-0.9.0.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 9/21/19 11:36 AM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraft.item.EnumRarity.getName()Ljava/lang/String;
	at austeretony.oxygen_trade.client.gui.trade.BuyGUISection.getRarityName(BuyGUISection.java:178)
	at austeretony.oxygen_trade.client.gui.trade.BuyGUISection.init(BuyGUISection.java:123)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.init(AbstractGUIScreen.java:51)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.func_73866_w_(AbstractGUIScreen.java:39)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1017)
	at austeretony.oxygen_core.client.api.ClientReference.displayGuiScreen(ClientReference.java:64)
	at austeretony.oxygen_trade.client.TradeMenuManagerClient.openTradeMenu(TradeMenuManagerClient.java:15)
	at austeretony.oxygen_trade.client.gui.trade.TradeMenuEntry.open(TradeMenuEntry.java:20)
	at austeretony.oxygen_menu.client.gui.menu.MenuGUISection.handleElementClick(MenuGUISection.java:31)
	at austeretony.alternateui.screen.button.GUIButton.mouseClicked(GUIButton.java:39)
	at austeretony.alternateui.screen.panel.GUIButtonPanel.mouseClicked(GUIButtonPanel.java:152)
	at austeretony.alternateui.screen.core.AbstractGUISection.mouseClicked(AbstractGUISection.java:133)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.func_73864_a(AbstractGUIScreen.java:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.func_146274_d(AbstractGUIScreen.java:173)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at austeretony.oxygen_trade.client.gui.trade.BuyGUISection.getRarityName(BuyGUISection.java:178)
	at austeretony.oxygen_trade.client.gui.trade.BuyGUISection.init(BuyGUISection.java:123)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.init(AbstractGUIScreen.java:51)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.func_73866_w_(AbstractGUIScreen.java:39)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1017)
	at austeretony.oxygen_core.client.api.ClientReference.displayGuiScreen(ClientReference.java:64)
	at austeretony.oxygen_trade.client.TradeMenuManagerClient.openTradeMenu(TradeMenuManagerClient.java:15)
	at austeretony.oxygen_trade.client.gui.trade.TradeMenuEntry.open(TradeMenuEntry.java:20)
	at austeretony.oxygen_menu.client.gui.menu.MenuGUISection.handleElementClick(MenuGUISection.java:31)
	at austeretony.alternateui.screen.button.GUIButton.mouseClicked(GUIButton.java:39)
	at austeretony.alternateui.screen.panel.GUIButtonPanel.mouseClicked(GUIButtonPanel.java:152)
	at austeretony.alternateui.screen.core.AbstractGUISection.mouseClicked(AbstractGUISection.java:133)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.func_73864_a(AbstractGUIScreen.java:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at austeretony.alternateui.screen.core.AbstractGUIScreen.func_146274_d(AbstractGUIScreen.java:173)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: austeretony.oxygen_trade.client.gui.trade.TradeMenuGUIScreen

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Titoo8899'/45, l='MpServer', x=1093.92, y=4.00, z=-764.05]]
	Chunk stats: MultiplayerChunkCache: 522, 522
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (915,4,51), Chunk: (at 3,0,3 in 57,3; contains blocks 912,0,48 to 927,255,63), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 235756 game time, 5500 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityVillager['Dorfbewohner'/48, l='MpServer', x=1073.53, y=4.00, z=-754.29], EntityPlayerSP['Titoo8899'/45, l='MpServer', x=1093.92, y=4.00, z=-764.05], NetherPortalEntity['entity.nether_portal.name'/46, l='MpServer', x=1019.50, y=5.50, z=-756.50], EndEntryPortalEntity['entity.end_entry_portal.name'/62, l='MpServer', x=1023.50, y=4.50, z=-747.50], EntityVillager['Dorfbewohner'/47, l='MpServer', x=1080.45, y=4.00, z=-759.26]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1940255344 bytes (1850 MB) / 3556769792 bytes (3392 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 74 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                         | Version               | Source                                                                  | Signature                                |
	|:--------- |:-------------------------- |:--------------------- |:----------------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                  | 1.12.2                | minecraft.jar                                                           | None                                     |
	| UCHIJAAAA | mcp                        | 9.42                  | minecraft.jar                                                           | None                                     |
	| UCHIJAAAA | FML                        | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar                                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                      | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar                                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | firstaidcore               | 1.0.0                 | minecraft.jar                                                           | None                                     |
	| UCHIJAAAA | mts                        | 14.3.1                | Immersive+Vehicles-1.12.2-14.3.1.jar                                    | None                                     |
	| UCHIJAAAA | mtsaircooled               | 1.0.0                 | Air-Cooled+Pack+[MTS]+1.10.2-14.0.0-BETA+1.0.0.jar                      | None                                     |
	| UCHIJAAAA | caveplus                   | 1.0.0                 | Better_Vanilla_1.3.jar                                                  | None                                     |
	| UCHIJAAAA | better_diving              | 1.3.91                | BetterDiving-1.12.2-1.3.91.jar                                          | None                                     |
	| UCHIJAAAA | forgelin                   | 1.8.4                 | Forgelin-1.8.4.jar                                                      | None                                     |
	| UCHIJAAAA | betterportals              | 0.3.5                 | betterportals-0.3.5.jar                                                 | None                                     |
	| UCHIJAAAA | unuparts                   | 2.0.3                 | UNU+Parts+Pack+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-2.0.3.jar                 | None                                     |
	| UCHIJAAAA | btcivil                    | 2.1.1                 | BlackThorne+Civilian+Vehicles+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-2.1.1.jar  | None                                     |
	| UCHIJAAAA | bookshelf                  | 2.3.588               | Bookshelf-1.12.2-2.3.588.jar                                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | capsule                    | 1.12.2-3.2.103        | Capsule-1.12.2-3.2.103.jar                                              | None                                     |
	| UCHIJAAAA | communism                  | 1.1                   | communism-1.1.2.jar                                                     | None                                     |
	| UCHIJAAAA | craftstudioapi             | 1.0.0                 | CraftStudio-1.0.0.93-mc1.12-alpha.jar                                   | None                                     |
	| UCHIJAAAA | crossbow                   | 1.0.0                 | Crossbow-Mod-1.12.2-1.0.0-fix.jar                                       | None                                     |
	| UCHIJAAAA | caliber                    | 1.2                   | diamond-caliber-v.1.3.jar                                               | None                                     |
	| UCHIJAAAA | fantasticlib               | 1.12.2.021            | FantasticLib-1.12.2.021.jar                                             | None                                     |
	| UCHIJAAAA | dynamicstealth             | 1.12.2.090            | DynamicStealth-1.12.2.090.jar                                           | None                                     |
	| UCHIJAAAA | mclib                      | 1.0.3                 | mclib-1.0.3-1.12.2.jar                                                  | None                                     |
	| UCHIJAAAA | emoticons                  | 0.3                   | emoticons-0.3-1.12.2.jar                                                | None                                     |
	| UCHIJAAAA | ftblib                     | 5.4.3.138             | FTBLib-5.4.3.138.jar                                                    | None                                     |
	| UCHIJAAAA | ftbguides                  | 2.0.0.47              | FTBGuides-2.0.0.47.jar                                                  | None                                     |
	| UCHIJAAAA | ftbutilities               | 5.4.0.106             | FTBUtilities-5.4.0.106.jar                                              | None                                     |
	| UCHIJAAAA | itemfilters                | 1.0.3.12              | ItemFilters-1.0.3.12.jar                                                | None                                     |
	| UCHIJAAAA | ftbquests                  | 1.7.2.218             | FTBQuests-1.7.2.218.jar                                                 | None                                     |
	| UCHIJAAAA | ftbmoney                   | 1.1.0.41              | FTBMoney-1.1.0.41.jar                                                   | None                                     |
	| UCHIJAAAA | ftbbackups                 | 0.0.0.ftbbackups      | FTBUtilitiesBackups-1.0.0.4.jar                                         | None                                     |
	| UCHIJAAAA | ivairlinerpack             | 1.0.0                 | Golden-Airport-Pack-_Immersive-Vehicles_-0.0.2.jar                      | None                                     |
	| UCHIJAAAA | grandeconomy               | 1.2.1                 | GrandEconomy-1.12.2-1.2.1.jar                                           | None                                     |
	| UCHIJAAAA | holdyerbreath              | 1.12.2-1.1.2          | holdyerbreath-1.12.2-1.1.2.jar                                          | None                                     |
	| UCHIJAAAA | waila                      | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                                             | None                                     |
	| UCHIJAAAA | mtsseagullcivilpack        | 2.0.0                 | Immersive+Vehicles+(IV)+Seagull's+civil+pack+1.22.0.jar                 | None                                     |
	| UCHIJAAAA | gramthanixpack             | 1.0.0                 | Immersive+Vehicles+(IV)+Seagull's+Gramthanix+Apocalyptic+pack+1.0.0.jar | None                                     |
	| UCHIJAAAA | mtsseagullmilitarypack     | 1.4.0                 | Immersive+Vehicles+(IV)+Seagull's+military+pack+1.7.4.jar               | None                                     |
	| UCHIJAAAA | mtsseagulltrinpartpack     | 1.0.0                 | Immersive+Vehicles+(IV)+Seagull's+trin+parts+pack+1.11.2.jar            | None                                     |
	| UCHIJAAAA | mdxlib                     | 3.0.0.20              | mdxlib-3.0.0.20.jar                                                     | None                                     |
	| UCHIJAAAA | lbm                        | 1.0                   | lbm-1.0.0.9.jar                                                         | None                                     |
	| UCHIJAAAA | letsencryptcraft           | @VERSION@             | letsencryptcraft-1.10.2-1.2.0.jar                                       | None                                     |
	| UCHIJAAAA | melvinssignpack            | 1.0.0                 | Melvins_Simple_Sign_Pack-Release-0.1.0.jar                              | None                                     |
	| UCHIJAAAA | mtsofficialpack            | 11.0.0                | MTS_Official_Pack_V11.jar                                               | None                                     |
	| UCHIJAAAA | merlynofficialpack         | 5.4.5                 | Merlyn's+Luxurious+Vehicles+Pack+5.4.5.jar                              | None                                     |
	| UCHIJAAAA | mmmpack                    | 1.0.3                 | Moonspire+Metropolitan+Motors+[MTS]+1.10.2-14.0.0-1.0.3.jar             | None                                     |
	| UCHIJAAAA | blueboyscaterpillarmtspack | 1.1.0                 | MTS_Caterpillar_Pack_V1.1.1.jar                                         | None                                     |
	| UCHIJAAAA | mtsheavyindustrialbyadamrk | 6.0.0                 | MTS_Heavy_Industrial_by_AdamRK_1.9.0.jar                                | None                                     |
	| UCHIJAAAA | jblavehaero                | 1.0.0                 | MTS_P1_airportpack.jar                                                  | None                                     |
	| UCHIJAAAA | oxygen_core                | 0.9.0                 | oxygen-core-1.12.2-0.9.0.jar                                            | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJAAAA | oxygen_cp_ge               | 0.9.0                 | oxygen-cp-grand-economy-1.12.2-0.9.0.jar                                | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJAAAA | oxygen_mail                | 0.9.0                 | oxygen-mail-1.12.2-0.9.0.jar                                            | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJAAAA | oxygen_menu                | 0.9.0                 | oxygen-menu-1.12.2-0.9.0.jar                                            | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJAAAA | oxygen_playerslist         | 0.9.0                 | oxygen-players-list-1.12.2-0.9.0.jar                                    | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJAAAA | oxygen_trade               | 0.9.0                 | oxygen-trade-1.12.2-0.9.0.jar                                           | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJAAAA | potioncore                 | 1.7_for_1.12.2        | PotionCore-1.7_for_1.12.2.jar                                           | None                                     |
	| UCHIJAAAA | projecttable               | 1.0                   | projecttable-1.12.2-0.1.3-universal.jar                                 | None                                     |
	| UCHIJAAAA | redcliffe                  | 1.0.1                 | RedCliffe+Republic+Vehicles+[MTS]+1.10.2-1.5.0-1.0.1.jar                | None                                     |
	| UCHIJAAAA | smm                        | 1.12.2-0.4            | ScrollableMainMenu-1.12.2-0.4.jar                                       | None                                     |
	| UCHIJAAAA | resourceloader             | 1.5.3                 | ResourceLoader-MC1.12.1-1.5.3.jar                                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | asf                        | 1.12.2                | rsix 1.jar                                                              | None                                     |
	| UCHIJAAAA | sleepingtubes              | 1.0.0                 | SleepingTubes_1.12.2_v1.0.jar                                           | None                                     |
	| UCHIJAAAA | cross                      | 1.12.2                | Some+New+Mobs-1.0.jar                                                   | None                                     |
	| UCHIJAAAA | stadiumcraft               | 1.0.0                 | StadiumCraft 1.12.2 Version 1.jar                                       | None                                     |
	| UCHIJAAAA | staminaplus                | 1.2                   | staminaplus-1.1.1.jar                                                   | None                                     |
	| UCHIJAAAA | tatami                     | 1.0.0                 | tatami-1.0.1.jar                                                        | None                                     |
	| UCHIJAAAA | tektopia                   | 1.1.0                 | tektopia-1.1.0.jar                                                      | None                                     |
	| UCHIJAAAA | tektopiainformation        | 1.2.0                 | TektopiaInformation-1.12.2-1.1.0-1.2.0.jar                              | None                                     |
	| UCHIJAAAA | t3gssksignspack            | 1.0.1                 | Tim3Game's+European+Signs+Pack+1.0.1.jar                                | None                                     |
	| UCHIJAAAA | toughasnails               | 3.1.0.141             | ToughAsNails-1.12.2-3.1.0.141-universal.jar                             | None                                     |
	| UCHIJAAAA | worldedit                  | 6.1.10-SNAPSHOT       | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar                       | None                                     |
	| UCHIJAAAA | firstaid                   | 1.6.3                 | firstaid-1.6.3.jar                                                      | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| UCHIJAAAA | jade                       | 0.1.0                 | Jade-0.1.0.jar                                                          | None                                     |
	| UCHIJAAAA | nofog                      | 1.12.2-1.12.2-1.0.3.0 | NoFog-1.12.2b3.jar                                                      | 0bf221d944c89aaf3ccb7b8315148f222be50739 |
	| UD        | mclib_core                 | 1.0.3                 | minecraft.jar                                                           | None                                     |

	Loaded coremods (and transformers): 
Currency Provider Core Plugin (oxygen-cp-grand-economy-1.12.2-0.9.0.jar)
  austeretony.oxygen_cp_ge.common.core.CurrencyProviderClassTransformer
Oxygen Core Plugin (oxygen-core-1.12.2-0.9.0.jar)
  austeretony.oxygen_core.common.core.plugin.OxygenClassTransformer
FMLModule (mdxlib-3.0.0.20.jar)
  com.asx.mdx.AccessTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
FirstAid CoreMod (firstaid-core-1.6.3.jar)
  ichttt.mods.firstaid.common.asm.PotionTransformer
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
Players List Core Plugin (oxygen-players-list-1.12.2-0.9.0.jar)
  austeretony.oxygen_playerslist.common.core.PlayersListClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3308' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

**Comment by AustereTony-MCMods** [comment]
Hello. Oxygen: Trade requires Forge 14.23.5.2838. Please, install the latest Forge version.
