### ISSUE TITLE
Trades can we not pick up with the newest version.

### ISSUE THREAD

**Issue by Titoo8899** [AustereTony-MCMods/Oxygen-Trade#3]
Hi,
I have testet and have from me thinks sell and then buy in Creative mode. The Money have the mod pick up and in History was the Items. But it give not function to pick up it then we have this trade. Please fix this. The best way is then we can the trade items we can pick up in the History area. Make it so, what we must right click on the item, and the interact put into the inventary.

**Comment by AustereTony-MCMods** [comment]
Bought and expired items, money for sold items are sent to the player by mail (Mail module).
