### ISSUE TITLE
Client-sided crash when creating trade offer

### ISSUE THREAD

**Issue by HRZNzero** [AustereTony-MCMods/Oxygen-Trade#4]
Upon creating a trade-offer (selling) the client crashed. 

This is the log from the anticrash mod we use:

https://paste.dimdev.org/orukopuxuy.mccrash

https://imgur.com/a/n9VbP3B

**Comment by TerdyTheTerd** [comment]
Do you know what was typed as the amount? Just passing through the code I see during that event there's an int cast from the text field but it has no exception handling on it. Based on that having something that can't be converted to an int would result in a crash. Could easily be something else though.

**Comment by AustereTony-MCMods** [comment]
Still have no idea... That part of code was greatly improved in 0.10.0b, so i hope this problem eliminated. In case any further issues create an ticket at Oxygen Core repo, please.
